name: Create Zip in Releases Folder
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create releases directory if it doesn't exist
        run: mkdir -p releases

      - name: Create zip file
        run: |
          # Create a zip file of source folder (change 'source' to your folder name)
          zip -r releases/release-$(date +'%Y%m%d_%H%M%S').zip source/ -x "*.git*"
          # If you want to zip the entire repository except releases folder:
          # zip -r releadd/release-$(date +'%Y%m%d_%H%M%S').zip . -x "*.git*" ".github/workflows/*" "releases/*"


      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add releases/
          git commit -m "Add new release zip file" || echo "No changes to commit"
          git push
